---
- name: install maven on Build-slave
  hosts: Build-slave
  become: true
  tasks:
  - name: install java
    ansible.builtin.apt:
      name: openjdk-17-jdk
      state: present
      update_cache: yes
  - name: install maven packages
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      dest: /opt/
  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /opt/apache-maven-3.9.9-bin.tar.gz
      dest: /opt/
      remote_src: yes
  